### ISSUE TITLE
how can mac book use it?

### ISSUE THREAD

**Issue by 13077598960** [freemansoft/jacob-project#14]
i had copy the dll  file to jre/bin
i use mac book
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jacob-1.18-x64 in java.library.path
 at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
 at java.lang.Runtime.loadLibrary0(Runtime.java:871)
 at java.lang.System.loadLibrary(System.java:1122)
 at com.jacob.com.LibraryLoader.loadJacobLibrary(LibraryLoader.java:184)
 at com.jacob.com.JacobObject.<clinit>(JacobObject.java:110)
 at com.cisco.jtapi.jacob.Speech.textToSpeech(Speech.java:20)
 at com.cisco.jtapi.jacob.Speech.main(Speech.java:15)

**Comment by freemansoft** [comment]
This is project is windows only.  It use Windows COM interface.

**Comment by 13077598960** [comment]
o,thx for reply
