### ISSUE TITLE
Getting com.jacob.com.ComFailException for SaveAs

### ISSUE THREAD

**Issue by agreeya-ankur** [freemansoft/jacob-project#25]
com.jacob.com.ComFailException: Invoke of: SaveAs
Source: Microsoft Word
Description: Command failed

	at com.jacob.com.Dispatch.invokev(Native Method)Invoke of: SaveAs
Source: Microsoft Word
Description: Command failed

	at com.jacob.com.Dispatch.invokev(Dispatch.java:625)
	at com.jacob.com.Dispatch.callN(Dispatch.java:453)
	at com.jacob.com.Dispatch.call(Dispatch.java:541)
	at Converter.main(Converter.java:54)
Exception in thread "main" java.lang.RuntimeException: pdf convert failed.
	at Converter.main(Converter.java:61)

**Comment by freemansoft** [comment]
Problem reports have no value without more details including sample code.

The error message says PDF conversion failed which does not look like a JACOB issue.
