### ISSUE TITLE
Windows service and VariantChangeType failed error

### ISSUE THREAD

**Issue by cholokla** [freemansoft/jacob-project#28]
Hello,
I have a problem running my app on Windows 11 as a service using WINSW (but also checked with NSSM).
It works properly as a standalone Java application and in all modes on Windows 10.

Code fragment that causes the problem:
```
ActiveXComponent objWord = new ActiveXComponent("Word.Application");
... setting Visible and FilePrintSetup here
Dispatch documents = objWord.getProperty("Documents").toDispatch();
Document document = Dispatch.call(documents, "Open", filename).toDispatch();
```

and the exception is:
```
Caused by: com.jacob.com.ComFailException: VariantChangeType failed
	at com.jacob.com.Variant.toVariantDispatch(Native Method)
	at com.jacob.com.Variant.toDispatch(Variant.java:2003)
```

Fragment of the log file with the Jacob debug flag on:
```
http-nio-18844-exec-2: Loading library jacob-1.20-x86 using System.loadLibrary 
http-nio-18844-exec-2: Loading library jacob-1.20-x86 using System.loadLibrary 
http-nio-18844-exec-2: Loading library jacob-1.20-x86 using System.loadLibrary 
http-nio-18844-exec-2: ComThread: before Init: 0
http-nio-18844-exec-2: ComThread: after Init: 0
http-nio-18844-exec-2: ROT: Automatic GC flag == false
http-nio-18844-exec-2: ComThread: after ROT.addThread: 0
http-nio-18844-exec-2: ROT: adding com.jacob.activeX.ActiveXComponent@19065e1->com.jacob.activeX.ActiveXComponent table size prior to addition:0
 http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:1
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:2
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:3
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:4
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:5
 http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:6
http-nio-18844-exec-2: ROT: adding com.jacob.com.Dispatch@47ec7b->com.jacob.com.Dispatch table size prior to addition:7
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:8
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:9
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:10
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:11
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:12
 http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:13
http-nio-18844-exec-2: ROT: adding com.jacob.com.Dispatch@125b27c->com.jacob.com.Dispatch table size prior to addition:14
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:15
http-nio-18844-exec-2: ROT: adding ->com.jacob.com.Variant table size prior to addition:16
```

Does anybody have any idea how to fix such problem?

Regards,
Robert

**Comment by cholokla** [comment]
Luckily, I've found a workaround.
After creating the folder "C:\Windows\SysWOW64\config\systemprofile\Desktop" everything seems to be working :)

**Comment by hen-corix** [comment]
In my case, it was the folder "C:\Windows\system32\config\systemprofile\Desktop" that needed to be created.
I think, @cholokla was running a 32-bit JDK or similar under a 64-bit Windows.
