### ISSUE TITLE
Dispatch.call open byte[]

### ISSUE THREAD

**Issue by tadashi0** [freemansoft/jacob-project#30]
我把文件转为byte[] ，但是报错，说找不到文档

**Comment by tadashi0** [comment]
我用的是1.20的版本

**Comment by tadashi0** [comment]
| |
田重辉
|
|
***@***.***
|
没有啊，哥们，这个Jacob只能去加载本地的文件！转%23是正常的，如果不行的话，可以对路径进行转义，然后再加载
---- Replied Message ----
| From | ***@***.***> |
| Date | 06/13/2023 14:25 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [freemansoft/jacob-project] Dispatch.call open byte[] (Issue #30) |

兄弟，你有没有遇到过这种问题，如果文件路径里带#，会转成%23，结果就找不着文件了
com.jacob.com.ComFailException: Invoke of: Open
Source: Microsoft Word
(D://abc/回复%23【中金-季报】国家能源投资集团有限责任公司企业...)

at com.jacob.com.Dispatch.invokev(Native Method)
at com.jacob.com.Dispatch.invokev(Dispatch.java:625)
at com.jacob.com.Dispatch.callN(Dispatch.java:453)
at com.jacob.com.Dispatch.call(Dispatch.java:541)

**Comment by sdabing** [comment]
我这本身原word文件路径带#，然后转pdf报错，怎么能不报错呢

**Comment by freemansoft** [comment]
Is this the same problem as the "space or other character" one?
