### ISSUE TITLE
Source: Microsoft Word  when directory contains '#', blank etc.

### ISSUE THREAD

**Issue by sdabing** [freemansoft/jacob-project#31]
com.jacob.com.ComFailException: Invoke of: Open
Source: Microsoft Word
 (D:\//abc/回复%23【中金-季报】国家能源投资集团有限责任公司企业...)

	at com.jacob.com.Dispatch.invokev(Native Method)
	at com.jacob.com.Dispatch.invokev(Dispatch.java:625)
	at com.jacob.com.Dispatch.callN(Dispatch.java:453)
	at com.jacob.com.Dispatch.call(Dispatch.java:541)
	at zor.fs.webservice.TransferPdfController.word2Pdf(TransferPdfController.java:158)
	at zor.fs.webservice.TransferPdfController.file2Pdf(TransferPdfController.java:103)
	at zor.fs.webservice.TransferPdfController.main(TransferPdfController.java:322)

**Comment by freemansoft** [comment]
Sample code?
